In [1]:
# ! uv pip install google
! uv pip install google-generativeai

Using Python 3.12.3 environment at: /home/rayudu/otherwork_assignment_all_jobs/Todo/ai_multi_agent_shopping_assistant/.venv
Checked 1 package in 3ms

In [2]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai
# Instead of: import openai
import google.generativeai as genai
from dotenv import load_dotenv
import os

2026-06-24 18:41:01.883369730 [W:onnxruntime:Default, device_discovery.cc:164 DiscoverDevicesForPlatform] GPU device discovery failed: device_discovery.cc:89 ReadFileContents Failed to open file: "/sys/class/drm/card0/device/vendor"
/tmp/ipykernel_2773170/3191430029.py:7: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

### Read the sampled dataset with Amazon inventory data

In [3]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [4]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[],169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...",[],24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN

In [5]:
list(df_items["features"].items())[0]

(0,
 ['【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger)',
  '【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more',
  '【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money.',
  '【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone.',
  "【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours."])

In [6]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51G07yWoOBL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51G07yWoOBL.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/611AVJMH+JL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41c+40oKkKL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41c+40oKkKL.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/61ihhPW7VCL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51y1YnwiUZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51y1YnwiUZL.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/61UkcVETKcL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41Nvr++q39L._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41Nvr++q39L.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/611IpDcRk3L._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41QrI+i4-lL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41QrI+i4-lL.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/61FQzaPa6jL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51lezEs5DvL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51lezEs5DvL.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71qz3TFInJL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/514a4NZS1ZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/514a4NZS1ZL.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/71e6ARGEtZL._SL1200_.jpg'}])

### Preprocess title and features

In [7]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [8]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [9]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [10]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51G07yWoOB...
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41bOA5-ogW...
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,USB C Docking Station Dual Monitor for MacBook...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN,https://m.media-amazon.com/images/I/416IzmVKiC...
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[2023 Upgraded] Telescopes for Adults Astronom...,169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41wO4J3TT0...
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...","Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41mwlYqT5p...

In [11]:
list(df_items["description"].items())[0]

(0,
 "RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB Type C Fast Charging Cord - Nylon Braided USB C Charger Cable for Galaxy A20/A50/S10/S9/S8+/S8, iPad Pro 2018, Sony XZ, HTC 10, OnePlus 5T, Huawei P9 etc. 【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger) 【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more 【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money. 【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone. 【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours.")

### Sample 50 items from the dataset

In [12]:
df_sample = df_items.sample(50, random_state=42)

In [13]:
len(df_sample)

50

In [14]:
data_to_embed = df_sample[["description", "image", "rating_number", "price", "average_rating", "parent_asin"]].to_dict(orient="records")

In [15]:
data_to_embed

[{'description': 'KEEPRO Pencil 2nd Generation for iPad, Magnetic Wireless Charge Tilt Sensitivity Palm Rejection Active Pen for Apple iPad Pro 11" 4/3/2/1, iPad Pro 12.9" 6/5/4/3, iPad Air 4/5, iPad Mini 6 [Compatibility]- ONLY compatible with iPad mini (6th generation), iPad Air (4th and 5th generation), iPad Pro 12.9-inch (3rd, 4th, 5th and 6th generation), iPad Pro 11-inch (1st, 2nd, 3rd and 4th generation), check and confirm your device before place the order (Note: If the pen doesn\'t charge, fully charge your iPad first then try charging the pen again) [Charging and Pairs Magnetically]- Charges wirelessly, attaches and pairs magnetically to the compatible iPad, this pen is a preferable alternative to the Apple Pencil 2nd Generation [Tilt Sensitivity & Pixel Precision]- Pixel-perfect precision and industry-leading low latency with tilt sensitivity making drawing, sketching, coloring, taking notes, and marking up PDFs, as easy and natural as a real pencil [Native Palm Rejection]- Rest your palm on the screen comfortably, allowing you to write and draw on your iPad as if it\'s an actual notebook [Hotkey for Easy Access]- Support Bluetooth connection to display battery percentage in the status bar, one-click return to the homepage, double-click to enter multi-task (long press 3s to turn On/Off) [Extra Replaceable Tips]- Come with 3 extra replaceable tips, keep extra tips for your pencil at the ready, the tip is compatible with Apple Pencil (1st generation) and Apple Pencil (2nd generation)',
  'image': 'https://m.media-amazon.com/images/I/21XciKpEmpL._AC_.jpg',
  'rating_number': 2131,
  'price': 22.97,
  'average_rating': 4.3,
  'parent_asin': 'B0BF18F6R7'},
 {'description': 'HOSONGIN 1/4 TRS Stereo Jack to Dual 1/4 TS Mono Y-Splitter Insert Cable, Nylon Braided Jacket Gold-Plated Plug Double Shielding Cable, 1 Feet EASILY CONNECT DEVICES: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch Y-Splitter Cable uses a 1/4" TRS stereo cable to connects a Mixer, Amplifier, Headphones, Speaker, or other devices with 6.35mm 1/4" TRS output to Hi-Fi stereo, speakers, or other pro audio gear with Dual 2x 6.35mm 1/4" TS Mono jack Stereo inputs. STANDARD CONNECTORS: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch TS Mono Y-Splitter Cable uses standard audio connectors, a 6.35mm(1/4 inch) TRS Female connector on one end, and two 1/4" TS Mono connectors on the other end. It splits a stereo signal into L-R audio over two 1/4 inch TS cables. CLEAN & CLEAR SOUND: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch TS Mono plug Y-Splitter Cable uses double shielded layers, tinned copper wire core, and corrosion-resistant gold-plated connector prevents EMI & RFI Signal Interference, ensuring the Highest Quality audio transfer without static or popping. STRONG DURABLE DESIGN: The HOSONGIN Audio Cable\'s Plugs with Aluminum Alloy Shell and Molding technology prolong service life; the beveled step-down design ensures a secure, fully plugged-in connection; the premium braided jacket exterior offers added strength and flexibility, tangle-free. AMAZING SHOPPING EXPERIENCE: You will get 1 x HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch Y-Splitter Cable, Not only that, you will become our forever VIP customer, and we will provide you with a full range of customer service and product services. Don\'t hesitate to contact us with any questions, and we will reply to you within 12 hours.',
  'image': 'https://m.media-amazon.com/images/I/41J3p7fyJHL.jpg',
  'rating_number': 114,
  'price': 14.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B96LV4C5'},
 {'description': 'Tenda A33 AX3000 WiFi 6 Extender, WiFi Booster WiFi Range Extender, 2.4/5GHz Dual Band WiFi Extender with Ethernet Port, AP Mode, WPS Easy Setup, WiFi Extenders Signal Booster for Home Improved WiFi Coverage - With 2 * 5dbi dual-band antennas, the Tenda A33 wifi extender can effectively boost your wifi signal for up to 2100 sq. ft coverage , providing you a stable wifi connection at your home with no dead zone. Fast Speed - Tenda A33 WiFi 6 Range Extender provides maximum speeds of 574Mbps on the 2.4GHz band and 2402Mbps on the 5GHz band, delivering you an unrivaled network experience at every corner of your house. More Devices, Less Latency - Compared with the previous WiFi 5 generation, WiFi 6 technology enables 1.5X better performance in speed and latency. You can connect to 20+ devices without issues like speed drop and network congestion. All-around WiFi Extender - Tenda A33 comes with a Gigabit Ethernet Port for demanding task like gaming and streaming. You can also use the access point mode to get the best possible speed from your network without worrying about interfering signal. Intelligent Roaming – Tenda A33 WiFi Repeater uses your existing network SSID name by default to ensure a seamless network experience around your home. Compatibility Note: The Tenda A33 is compatible with 99% wifi routers in the market. However, if you want to extend a mesh network, adding a mesh node would be recommended as most mesh systems remove the "AP Client" feature that is necessary for a wifi extender to work.',
  'image': 'https://m.media-amazon.com/images/I/31dq3Sl6OnL._AC_.jpg',
  'rating_number': 560,
  'price': 84.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BZ5R7CVP'},
 {'description': 'Bluetooth Transmitter Receiver, 5.0 Bluetooth Adapter with 3.5mm RCA TF Card Playback, 2-in-1 Audio Adapter, Bluetooth Car Adapter for PC/TV/Speaker/Headphones/Home Low Latency 【2-In-1 Bluetooth Transceiver】 In the transmitter mode, the Bluetooth adapter can be paired with a Bluetooth headset or speaker. In the receiver mode, it can be connected to the traditional wired speaker stereo receiver, the auxiliary input port of the car adapter, make them wireless, and connect the mobile phone or tablet to play your favorite music. 【Featured TF Card Slot】Fossduck bluetooth adapter for stereo receiver is featured for the TF card slot. You can choose either to play from your smart device or TF card! No matter you are using an old speaker, vintage stereo, or car stereo system, you can easily turn the music into wireless via the 3.5 mm or RCA cables of the bluetooth audio receiver. 【LED Display Screen & Button Control】 The display will show the Bluetooth status, and press the previous/next track key at the same time to switch the transmit and receive mode 【Great Sound Quality】Fossduck bluetooth transmitter receiver can transmit stereo audio wirelessly from your non-bluetooth audio sources such as tv, mp3, cd player, pc or ebook reader to your bluetooth-enabled headphones, speaker or receiver. This way, you can enjoy high quality music wirelessly or listen to late night shows without disturbing your loved ones while they sleep. 【Wide Cover Range】Fossduck stereo receiver with bluetooth can cover up to 50-70ft range with a reliable connection. No more wires limit and definitely offer you much more convenience with a fluent, enjoyable music experience',
  'image': 'https://m.media-amazon.com/images/I/41ih5c0-XkL._AC_.jpg',
  'rating_number': 220,
  'price': nan,
  'average_rating': 3.9,
  'parent_asin': 'B09PFSVK44'},
 {'description': 'iPhone Charger Cord Lightning Cables, Original 2022 Upgraded [3Pack 3ft] Apple MFi Certified USB A Charging Cable for iPhone 13 12 11 Mini Pro XR Xs Max X SE 8 7 6 Plus iPad iPod AirPods - Black Original Apple Cable - iPhone charging cable with a reinforced joint design that has passed 30,000+ times bending tests for extra protection and durability. Insulation and precisely layer-welded connectors, which make the cable more durable and sturdier than normal iPhone charger cables but also flexible and tangle-free. Instant Responses - No error message pops up. Real high-speed iPhone charging cable with stable and efficient current output, you can plug it into laptop computers and in-car charging adapter. Super Fast Charge - The iPhone Lightning cable build-in four-core high-quality copper wires and multiple safety protections overcharge/stable current/automatic switching/battery protection to promote maximum signal quality and strength. You can enjoy faster charging [3.0A] and safer high-speed data transferring [480Mbps]. Apple MFi Certified - Lightning cable ensure 100% compatibility with iPhone 13, 13 Pro, 13 Pro Max, 13 Mini, 12, 12 Mini, 12 Pro, 12 Pro Max, SE 2020, iPhone 11, 11 Pro, 11 Pro Max, XR , Xs , Xs Max, X, 8, 8 plus, 7, 7 plus, 6s, 6s plus, 6, 6 plus, SE, 5s, 5, 5c, iPad Pro, iPad Air, iPad Air 2, iPad mini, mini 2, mini 3, mini 4, Mini 6, iPad 4, iPad 9, iPod Touch (5 Gen), iPod Nano 7. What You Get? - 3-foot long MFI apple certified iPhone charger cable 3 pack, if you have any questions, please feel free to contact us. Notice: Please make sure to make a purchase in the store! Otherwise, we will not be able to guarantee its authenticity, and we do not provide any after-sale services for other stores!',
  'image': 'https://m.media-amazon.com/images/I/41lk7yDhf3L.jpg',
  'rating_number': 4709,
  'price': 12.59,
  'average_rating': 4.5,
  'parent_asin': 'B0BYYLJRHT'},
 {'description': 'Punoge Small USB Desk Fan - 5.3 Inch Portable Table Fan with 3 Levels Air Flow, 8 Color LED Lights, 360° Rotation, Quiet Mini Personal Fan for Home Office Desktop Innovative Portable Desk Fan - Why bring a boring fan to your home if you can find such a distinctive one with 3 adjustable wind speed, 8 different color light and 360° Rotatable stand? With its small size: 5.5* 3.5* 5.8in (14.1*9*14.7cm), you could put it anywhere on the tabletop of your home or office. Say goodbye to hot flashes, sweating, and flushing from now on 3 Levels Wind Speed Adjustable - This table fan provides 3 levels air flow for you to choose from. Just press one button you could select a comfortable wind speed. The maximum speed of this desk fan is up to 3300 RPM, so you get instant cool feeling as soon as you turn it on. And it’s quiet enough for you to use at home or office, the wind noise is below 45dB for the lowest level 8 Colors Atmosphere Light - This personal fan is equipped with 8 different colors LED light function. One press of the light button you could switch to the color you like, you will no longer feel boring when you’re working or gaming in hot weather. This desktop fan would also be a great gift choice USB Powered - The table fan is powered by a 4.9ft USB cable, you can plug it into all USB ports like laptops, computer, power banks or other USB-enabled power supplies. NOTE: This USB fan do not contain any battery, and it’s not rechargeable Premium Tabletop Fan - 360° rotatable fan to provide wind in any desired direction. Smooth and sleek design made of high grade ABS material, makes it a modern decor for your home or office. What you get: A Desk Fan with USB cable, a User Manual',
  'image': 'https://m.media-amazon.com/images/I/41ttrJKbfFL._AC_.jpg',
  'rating_number': 117,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B0B1MPKCS8'},
 {'description': '8 Pairs Powerbeats Pro Ear Tips Buds, 4 Size Replacement Soft Flexible Fit in Case Noise Reduce Silicone Rubber Earbuds Eartips Wing Skin Accessories Compatible with Beats Flex/BeatsX - White 【 Compatibility 】 These ear tips compatible with Powerbeats Pro, compatible with Powerbeats High Performance, compatible with Beats Flex, compatible with Beats X, compatible with Beats Fit Pro, compatible with Beats Studio Buds. 【 Material 】 Made of soft flexible premium silicone, provide more noise isolation, in-ear stability and a lasting comfort. And They are Water-washable, durable, flexible, removable and replaceable. 【 Nice Sound Quality 】 These ear tips can offer a good seal to reduce some of the outside noise and allow you to focus on your audio, provide a better sound listening experience. 【 More Size Options, Better Fit 】 Small Medium Large and Double Flange 4 different sizes, complies comfortably with your individual ear shape. Fit in the charging case, no need to remove the foam when you put earphone into the charging case. 【 Package include 】 8 pairs replacement ear tips, tips only, earphone not include.',
  'image': 'https://m.media-amazon.com/images/I/31Q1I3K1KuL._AC_.jpg',
  'rating_number': 269,
  'price': 7.99,
  'average_rating': 4.5,
  'parent_asin': 'B0B14HTZ59'},
 {'description': 'Crodi Engraved Christmas & Halloween Band Compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense Band Women Men Fadeless Pattern Silicone Sports Solo Loop Soft Strap ONLY for Versa 4/Sense 2 Buckle closure 🎄Fadeless Christmas Watch Band: The engraved Christmas Tree pattern from the unique design inspiration that makes it stand out from traditional silicone bands. The engraving process allows the pattern on the band to last for a long time without fading. This strap adds character to your Versa 4/Versa 3/Sense 2/Sense smartwatch band. 🎄Skin-friendly material with classic Clasp design: Made of skin-friendly silicone material, it is waterproof and dustproof while reducing the occurrence of skin irritation. The washable feature allows it to excel in sports, beach vacations, and hot weather.Best of all, having a real buckle instead of those studs that push through the hole, keeps it secure on wrist. 🎄A universal band for many occasions: A stylish and unique band for anyone. Whether it\'s for sports, travel, party, work, or just hanging out it can be the perfect match for your watch. Add fashionable and trendy style to you. It is only compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense smartwatch. Please confirm your watch model before purchase. 🎄Attractive, Sweet and Practical Gift:It has enough holes for length adjustment and can fit wrists from 5.25"-7.3". The unique printed wristband with posh embossed Christmas pattern design gives you a lightweight, soft, youthful and energetic feeling. it can be a stylish gift for family friends or lovers. 🎄Enjoy Your Watch Band: One-year warranty,and 24/7 online service.We will refund or free replacement if you have any concerns or dissatisfaction.（Watches NOT Include） We will do our best to keep providing better products and better service.',
  'image': 'https://m.media-amazon.com/images/I/41oB2HWqMUL._AC_.jpg',
  'rating_number': 112,
  'price': 6.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BB1YKXL1'},
 {'description': "MUXA 6 Pack [Apple MFi Certified] 3/3/6/6/10/10 FT iPhone Charger Colorful Nylon Lightning Cable Compatible iPhone 13 mini/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S/6/SE/5S/iPad ♦Perfectly Compatibility♦ : Work with iPhone 13 12 11, 13 12 11 Pro, 13 12 11 Pro Max,13 12 Mini, XS Max, XS, XR, X, 8 Plus, 8, 7 Plus, 7, 6S Plus, 6S, 6 Plus, 6, 5S, 5C, 5, iPad iPod . ♦Multiple Enjoyment♦ : Precise interface design, Fits enoughly to your charging port, no need to remove the phone case, solve tedious troubles, and charge when you want to charge all the time.Cables long enough to be convenient to charge your device in bedroom, sofa, office, travel，even when you are on the backseat of the car. ♦MFi Certified iPhone Charger♦ : MFI Certified Lightning Cable, Built with terminal and smart chip, ensured safe charging for your devices and Enjoy fast charge and data transfer. ♦Strengthened Durability♦ : It will be more durable than iPhone cable you have ever seen. It has a service life of 12 times longer than other cables, and has been proven to withstand 12,000 cycles + bending in rigorous laboratory tests. ♦Sweet Service♦ : If you have any questions about the product, please don't hesitate to contact us immediately and we will answer you within 24 hours.",
  'image': 'https://m.media-amazon.com/images/I/61rpS-eHRTL.jpg',
  'rating_number': 3922,
  'price': 11.99,
  'average_rating': 4.5,
  'parent_asin': 'B09TNXY54Y'},
 {'description': '1TB USB Flash Drives, NEIGHBOR Portable Thumb Drive 1TB USB Memory Stick, Metal 1000GB USB Drive High-Speed Waterproof Jump Drive for Data Storage and Transfer 【Reliable & Durable】The usb memory stick adopts Grade-A chips and high quality flash memory particles, safeguards your data and transfers your data seamlessly. Quicker heat dissipation permits longer service life. Suitable for storing digital data for school, business or daily usage. With Small size, these flash drives are readily available wherever you go. 【Excellent Compatibility】Ultra High Speed 1TB Flash Memory Stick is plug and play without any software installation; Simply insert the USB 3.0 Pen Drive 1000GB into the device to transfer and store data between the devices. The USB Flashdrives Supports Windows 7/8/10 / Vista / XP / Unix / 2000 / ME / NT Linux and Mac OS, and is compatible with USB 1.1, USB 2.0 and USB 3.0 ports. 【High Quality】USB Flash Drive 1TB features durable and rugged Metal housing body. The inside uses the most advanced imported smart chip, assembled through many complicated and strict processes. Therefore, it has excellent water resistance, magnetic resistance, high-temperature resistance, and X-ray resistance, thus ensuring that its service life far exceeds other similar products, which makes you store your data with more confidence. 【Powerful Storage Functions】USB Thumb Drive 1TB can transfer up to 204800 photos[10 megapixels]; 102400 MP3 audio files; 2560 minutes HD videos[1080P resolution] or 5120 minutes HD videos [720P resolution]. 1TB Flash Memory Stick is commonly used for storage, data backup and computer file transfer, it will meet your needs of daily use on work, school, home, and traveling for photos, music, videos, files storage and transfer. 【24 Hour Warm Customer Service】USB flash drive 1000GB widely use on personal use and meet your business needs in daily life.We always try our best to provide 100% customer satisfaction.Please click contact us if you have any quality issues.We are always here to address your problem in 24 hours.',
  'image': 'https://m.media-amazon.com/images/I/31jZHJYSgfL._AC_.jpg',
  'rating_number': 107,
  'price': 25.99,
  'average_rating': 4.8,
  'parent_asin': 'B0CF57H28T'},

### Define the embedding function

In [20]:
# response = openai.embeddings.create(
#     input="Random text",
#     model="text-embedding-3-small",
# )

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

In [ ]:
# len(response.data[0].embedding)

In [ ]:
# def get_embedding(text, model="text-embedding-3-small"):
#     response = openai.embeddings.create(
#         input=text,
#         model=model,
#     )
#     return response.data[0].embedding

In [ ]:
# get_embedding("Hi")

In [16]:
from google import genai

gemini_client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

response = gemini_client.models.generate_content(
    model="gemini-2.5-flash",
    contents=["You are a helpful assistant",
              "can you print 15 random words?"]
)

print(response.text)

ValueError: Missing key inputs argument! To use the Google AI API, provide (`api_key`) arguments. To use the Google Cloud API, provide (`vertexai`, `project` & `location`) arguments.

In [23]:
def get_embedding(text, model="models/text-embedding-004", task_type="RETRIEVAL_DOCUMENT"):
    """
    task_type="RETRIEVAL_DOCUMENT" is best practice for data going INTO your database.
    We will use task_type="RETRIEVAL_QUERY" when searching.
    """
    response = gemini_client.embed_content(
        model=model,
        content=text,
        task_type=task_type
    )
    return response['embedding']

In [24]:
get_embedding("Hi")

NameError: name 'gemini_client' is not defined

### Create Qdrant collection

In [ ]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [ ]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

### Embed data

##### Test

In [ ]:
pointstruct = PointStruct(
    id=0,
    vector=get_embedding("Test text"),
    payload={
        "text": "Test text",
        "model": "text-embedding-3-small",
    },
)

In [ ]:
pointstruct

### Amazon data

In [ ]:
pointstructs = []
for i, data in enumerate(data_to_embed):
    embediing = get_embedding(data["description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embediing,
            payload=data,
        )
    )

In [ ]:
pointstructs

In [ ]:
len(pointstructs)

### Write embedded data to Qdrant

In [ ]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01",
    wait=True,
    points=pointstructs,
)

### Define a function for data retrieval

In [ ]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-00",
        query=query_embedding,
        limit=k,
    )
    return results

### Test retrieval

In [ ]:
retrieve_data("What kind of charging cords do you offer?", k=10).points